param([string]$OutputPath="")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
$root=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path);$tpl=Join-Path $root "Hướng_dẫn_đồ_án\MAU Bao cao do an.pptx";if(!$OutputPath){$OutputPath=Join-Path $root "docs\PowerPoint_Bao_cao_do_an_HomeX_POS.pptx"};$pdf=[IO.Path]::ChangeExtension($OutputPath,".pdf");$prev="D:\tmp\homex-template-ppt-preview";$dr=Join-Path $root "docs\images";$ui=Join-Path $root "Nguyễn Đức Thịnh_2305CT2084_CT07PM\1_UI website\Admin";$logo=Join-Path $dr "logo_hvu.png"
$A=@{Use=Join-Path $dr "01_use_case_tong_quat.png";ERD=Join-Path $dr "13_erd_rut_gon.png";Sales=Join-Path $ui "02.4_pos_tro_ly_ai_goi_y.jpg";InvAI=Join-Path $ui "10.2_kho_hang_tro_ly_ai.jpg";Product=Join-Path $ui "07.5_san_pham_them_moi.jpg";Dash=Join-Path $ui "01.1_tong_quan_dashboard.jpg";Pos=Join-Path $ui "02.1_pos_giao_dien_chinh.jpg";Pay=Join-Path $ui "02.6_pos_thanh_toan_payos.jpg";Inv=Join-Path $ui "10.1_kho_hang_tong_quan.jpg";War=Join-Path $ui "05.3_bao_hanh_chi_tiet.jpg"}
function RGB($r,$g,$b){$r+256*$g+65536*$b};$N=RGB 16 32 96;$R=RGB 224 16 32;$TX=RGB 20 24 32;$M=RGB 80 90 106;$WH=RGB 255 255 255;$OF=RGB 247 249 252;$BD=RGB 211 220 232;$G=RGB 27 137 91;$AM=RGB 226 145 31;$SB=RGB 234 240 251;$SR=RGB 255 238 240;$SG=RGB 232 247 240
function T($s,$t,$x,$y,$w,$h,$z=22,$c=$TX,$b=$false,$a=1,$v=1){$q=$s.Shapes.AddTextbox(1,$x,$y,$w,$h);$q.TextFrame.TextRange.Text=$t;$q.TextFrame.WordWrap=-1;$q.TextFrame.MarginLeft=2;$q.TextFrame.MarginRight=2;$q.TextFrame.VerticalAnchor=$v;$q.TextFrame.TextRange.Font.Name="Aptos";$q.TextFrame.TextRange.Font.Size=[single]$z;$q.TextFrame.TextRange.Font.Bold=if($b){-1}else{0};$q.TextFrame.TextRange.Font.Color.RGB=$c;$q.TextFrame.TextRange.ParagraphFormat.Alignment=$a;$q.TextFrame.AutoSize=0;$q.TextFrame2.AutoSize=0;$q.Width=$w;$q.Height=$h;$q}
function B($s,$x,$y,$w,$h,$f=$WH,$l=$BD,$wt=1){$q=$s.Shapes.AddShape(5,$x,$y,$w,$h);$q.Fill.Solid();$q.Fill.ForeColor.RGB=$f;if($wt-le0){$q.Line.Visible=0}else{$q.Line.Visible=-1;$q.Line.ForeColor.RGB=$l;$q.Line.Weight=[single]$wt};$q}
function Pic($s,$p,$x,$y,$w,$h){if(!(Test-Path $p)){return};$im=[Drawing.Image]::FromFile($p);try{$sc=[Math]::Min($w/$im.Width,$h/$im.Height);$pw=$im.Width*$sc;$ph=$im.Height*$sc}finally{$im.Dispose()};$s.Shapes.AddPicture($p,0,-1,$x+($w-$pw)/2,$y+($h-$ph)/2,$pw,$ph)|Out-Null}
function Shot($s,$p,$x,$y,$w,$h,$lab){B $s $x $y $w $h|Out-Null;Pic $s $p ($x+6) ($y+6) ($w-12) ($h-32);T $s $lab ($x+8) ($y+$h-25) ($w-16) 20 12 $N $true 2 3|Out-Null}
function Prep($s,$title){foreach($q in @($s.Shapes)){try{if($q.PlaceholderFormat.Type-eq1){$q.TextFrame.TextRange.Text=$title;$q.TextFrame.TextRange.Font.Name="Aptos Display";$q.TextFrame.TextRange.Font.Size=44;$q.TextFrame.TextRange.Font.Bold=-1}elseif($q.PlaceholderFormat.Type-eq7){$q.Delete()}}catch{}}}
function Card($s,$title,$body,$x,$y,$w,$h,$ac=$N){B $s $x $y $w $h $OF|Out-Null;$r=$s.Shapes.AddShape(1,$x,$y,6,$h);$r.Fill.Solid();$r.Fill.ForeColor.RGB=$ac;$r.Line.Visible=0;T $s $title ($x+18) ($y+12) ($w-30) 28 19 $N $true|Out-Null;T $s $body ($x+18) ($y+45) ($w-30) ($h-53) 16 $M|Out-Null}
function Met($s,$val,$lab,$x,$y,$w,$ac,$f){B $s $x $y $w 112 $f $f 0|Out-Null;T $s $val ($x+12) ($y+8) ($w-24) 44 28 $ac $true|Out-Null;T $s $lab ($x+12) ($y+58) ($w-24) 40 16 $TX $true|Out-Null}
function Check($s,$t,$x,$y,$w){$c=$s.Shapes.AddShape(9,$x,$y+3,21,21);$c.Fill.Solid();$c.Fill.ForeColor.RGB=$SG;$c.Line.Visible=0;T $s "✓" $x ($y+2) 21 21 12 $G $true 2 3|Out-Null;T $s $t ($x+29) $y ($w-29) 28 17 $TX $true 1 3|Out-Null}
function Note($s,$t){try{foreach($q in $s.NotesPage.Shapes){if($q.Type-eq14-and$q.PlaceholderFormat.Type-eq2){$q.TextFrame.TextRange.Text=$t;break}}}catch{}}
$app=$null;$p=$null
try{$app=New-Object -ComObject PowerPoint.Application;$app.Visible=-1;$p=$app.Presentations.Open($tpl,$false,$false,$false)
$s=$p.Slides.Item(1);foreach($q in $s.Shapes){if($q.Type-eq17){$q.TextFrame.TextRange.Text="BÁO CÁO ĐỒ ÁN TỐT NGHIỆP - XÂY DỰNG VÀ TRIỂN KHAI WEBSITE POS CHO CỬA HÀNG ĐỒ GIA DỤNG HOMEX";$q.TextFrame.TextRange.Font.Name="Times New Roman";$q.TextFrame.TextRange.Font.Size=34;$q.TextFrame.TextRange.Font.Bold=-1}else{try{if($q.PlaceholderFormat.Type-eq3){$q.TextFrame.TextRange.Text="TRƯỜNG ĐẠI HỌC HÙNG VƯƠNG TP.HCM - KHOA KỸ THUẬT CÔNG NGHỆ"}elseif($q.PlaceholderFormat.Type-eq4){$q.TextFrame.TextRange.Text="Sinh viên thực hiện: Nguyễn Đức Thịnh; Mã số sinh viên: 2305CT2084; Khoá: 2023 - 2027; Giảng viên hướng dẫn: ThS. Nguyễn Thanh Tiến";$q.TextFrame.TextRange.Font.Name="Times New Roman";$q.TextFrame.TextRange.Font.Size=22}}catch{}}};Note $s "Giới thiệu đề tài HomeX POS."
$s=$p.Slides.Item(2);Prep $s "GIỚI THIỆU ĐỀ TÀI – LÝ DO CHỌN ĐỀ TÀI";$d=@("Cửa hàng đồ gia dụng có nhiều SKU, giá bán và chính sách bảo hành.","Quy trình thủ công làm dữ liệu đơn hàng, kho và khách hàng rời rạc.","Sai lệch một giao dịch ảnh hưởng tiền quỹ, tồn kho và bảo hành.","HomeX POS tập trung dữ liệu và tự động hóa bán hàng tại quầy.","Phạm vi: một cửa hàng, một kho, Admin và Cashier.");for($i=0;$i-lt5;$i++){T $s ("• "+$d[$i]) 86 (160+58*$i) 788 48 22 $TX|Out-Null};Note $s "Nêu lý do chọn đề tài và phạm vi."
$s=$p.Slides.Item(3);Prep $s "PHÂN TÍCH ĐỀ TÀI";Card $s "Mục tiêu" "Liên kết POS, thanh toán, kho, khách hàng và sau bán." 66 155 250 142 $N;Card $s "Đối tượng" "Admin; Cashier; khách hàng thanh toán và tra cứu." 355 155 250 142 $R;Card $s "Phạm vi" "Một cửa hàng, một kho; chưa đa chi nhánh." 644 155 250 142 $G;Card $s "Chức năng cốt lõi" "POS • PayOS • Kho • Bảo hành • Hoàn trả • VAT • Báo cáo • Audit log" 66 325 828 125 $N;Note $s "Tóm tắt mục tiêu, đối tượng, phạm vi và chức năng."
$s=$p.Slides.Item(4);Prep $s "PHÂN TÍCH HỆ THỐNG";T $s "KIẾN TRÚC" 75 150 230 24 17 $N $true 2 3|Out-Null;T $s "USE CASE" 365 150 230 24 17 $N $true 2 3|Out-Null;T $s "DỮ LIỆU" 655 150 230 24 17 $N $true 2 3|Out-Null;B $s 72 183 240 255 $OF|Out-Null;T $s "NEXT.JS" 95 205 194 38 22 $N $true 2 3|Out-Null;T $s "↓" 155 247 75 30 22 $R $true 2 3|Out-Null;T $s "EXPRESS API" 95 280 194 38 22 $N $true 2 3|Out-Null;T $s "↓" 155 322 75 30 22 $R $true 2 3|Out-Null;T $s "PRISMA + POSTGRESQL" 85 355 214 46 18 $N $true 2 3|Out-Null;Pic $s $A.Use 352 183 256 255;Pic $s $A.ERD 642 183 256 255;Note $s "Trình bày kiến trúc, use case và ERD."
$s=$p.Slides.Item(5);Prep $s "ỨNG DỤNG AI TRONG ĐỒ ÁN";$d=@(@("Trợ lý bán hàng","LLM gợi ý trên tập sản phẩm kiểm soát",$A.Sales,$N),@("Ước lượng nhập","Công thức tính; LLM chỉ diễn giải",$A.InvAI,$R),@("Barcode và ảnh","Điền trường thiếu; người dùng duyệt",$A.Product,$G));for($i=0;$i-lt3;$i++){$x=66+282*$i;B $s $x 153 260 300|Out-Null;T $s $d[$i][0] ($x+12) 164 236 30 18 $d[$i][3] $true 2 3|Out-Null;Pic $s $d[$i][2] ($x+12) 205 236 140;T $s $d[$i][1] ($x+14) 357 232 70 15 $TX|Out-Null};Note $s "Phân biệt rõ ba chức năng hỗ trợ thông minh."
$s=$p.Slides.Item(6);Prep $s "KẾT QUẢ ĐẠT ĐƯỢC";Met $s "10 / 10" "Webhook PayOS" 66 158 185 $G $SG;Met $s "8 / 8" "Trợ lý bán hàng" 272 158 185 $N $SB;Met $s "21 / 21" "Bất biến nhập hàng" 478 158 185 $N $SB;Met $s "33,3%" "Nhận dạng tên ảnh" 684 158 185 $R $SR;Check $s "Backend TypeScript: không lỗi" 80 315 375;Check $s "Frontend build: 28 route" 80 362 375;Check $s "Benchmark JSON chạy lại được" 80 409 375;B $s 505 314 365 125 $OF $OF 0|Out-Null;T $s "Build không thay thế unit, integration, kiểm thử tải hoặc đánh giá người dùng thật." 525 340 320 75 17 $TX|Out-Null;Note $s "Trình bày kết quả kiểm thử và giới hạn."
$s=$p.Slides.Item(7);Prep $s "KẾT QUẢ ĐẠT ĐƯỢC – ĐÁNH GIÁ BẢO MẬT";T $s "PAYOS WEBHOOK" 66 153 240 28 20 $R $true|Out-Null;$d=@("Xác minh chữ ký webhook","Chống replay","Idempotency theo mã đơn","Đối chiếu số tiền","Đối chiếu orderCode","Không tin trạng thái frontend","Client đóng vẫn hoàn tất","Ghi nhật ký giao dịch");for($i=0;$i-lt8;$i++){Check $s $d[$i] (72+405*($i%2)) (202+52*[Math]::Floor($i/2)) 365};B $s 66 425 804 38 $SB $SB 0|Out-Null;T $s "Frontend không có quyền quyết định đơn hàng đã thanh toán." 78 429 780 30 17 $N $true 2 3|Out-Null;Note $s "Nêu các kiểm soát bảo mật PayOS."
$s=$p.Slides.Item(8);Prep $s "DEMO SẢN PHẨM";Shot $s $A.Dash 66 150 190 130 "Dashboard";Shot $s $A.Pos 270 150 190 130 "Bán hàng POS";Shot $s $A.Pay 474 150 190 130 "PayOS";Shot $s $A.Inv 678 150 190 130 "Kho hàng";Shot $s $A.War 168 305 250 135 "Bảo hành";Shot $s $A.InvAI 516 305 250 135 "Hỗ trợ nhập";T $s "Xin mời quý thầy cô xem demo sản phẩm" 180 455 600 30 22 $R $true 2 3|Out-Null;Note $s "Demo theo luồng từ POS đến kho và bảo hành."
$s=$p.Slides.Item(9);Prep $s "KẾT LUẬN";$d=@("Đã liên kết POS, thanh toán, kho, khách hàng và sau bán.","Webhook PayOS có xác minh, đối chiếu và idempotency.","Hệ thống build thành công và có benchmark tái lập.","Ước lượng tồn kho chưa vượt baseline nên chỉ dùng tham khảo.","Hướng phát triển: dữ liệu thực, đa kho, serial/lô và test tự động.");for($i=0;$i-lt5;$i++){T $s ("• "+$d[$i]) 82 (155+60*$i) 800 52 21 $TX|Out-Null};Note $s "Kết luận và hướng phát triển."
$s=$p.Slides.Item(10);Prep $s "CẢM ƠN";Pic $s $logo 390 155 180 180;T $s "TRÂN TRỌNG CẢM ƠN QUÝ THẦY CÔ ĐÃ CHÚ Ý THEO DÕI!" 120 355 720 54 26 $N $true 2 3|Out-Null;T $s "Q & A" 350 425 260 50 32 $R $true 2 3|Out-Null;Note $s "Cảm ơn và trả lời câu hỏi."
$p.SaveAs($OutputPath,24);$p.SaveCopyAs($pdf,32);if(Test-Path $prev){Remove-Item $prev -Recurse -Force};New-Item -ItemType Directory $prev -Force|Out-Null;$p.Export($prev,"PNG",1280,720);Write-Output "pptx=$OutputPath";Write-Output "pdf=$pdf";Write-Output "slides=$($p.Slides.Count)"
}finally{if($p){$p.Close()};if($app){$app.Quit()};if($p){[Runtime.InteropServices.Marshal]::ReleaseComObject($p)|Out-Null};if($app){[Runtime.InteropServices.Marshal]::ReleaseComObject($app)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
