export const USER_ROLES = {
  ADMIN: "ADMIN",
  CASHIER: "CASHIER",
} as const;

export const RECORD_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export const ORDER_STATUS = {
  DRAFT: "DRAFT",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const PAYMENT_STATUS = {
  PAID: "PAID",
  PENDING: "PENDING",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
} as const;

export const PAYMENT_METHOD = {
  CASH: "CASH",
  CARD: "CARD",
  TRANSFER: "TRANSFER",
  WALLET: "WALLET",
} as const;

export const STOCK_TRANSACTION_TYPE = {
  IMPORT: "IMPORT",
  SALE: "SALE",
  ADJUSTMENT: "ADJUSTMENT",
  RESTORE: "RESTORE",
} as const;

export const WARRANTY_STATUS = {
  ACTIVE: "ACTIVE",
  CLAIMED: "CLAIMED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
} as const;

export const AUDIT_ACTION = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  RESTORE: "RESTORE",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  IMPORT_STOCK: "IMPORT_STOCK",
  ADJUST_STOCK: "ADJUST_STOCK",
  CREATE_DRAFT_ORDER: "CREATE_DRAFT_ORDER",
  UPDATE_DRAFT_ORDER: "UPDATE_DRAFT_ORDER",
  CHECKOUT_ORDER: "CHECKOUT_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
  UPDATE_PAYMENT_STATUS: "UPDATE_PAYMENT_STATUS",
  CREATE_WARRANTY: "CREATE_WARRANTY",
  CANCEL_WARRANTY: "CANCEL_WARRANTY",
  RESTORE_WARRANTY: "RESTORE_WARRANTY",
  EXPIRE_WARRANTY: "EXPIRE_WARRANTY",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
} as const;

export const AUDIT_ENTITY_TYPE = {
  USER: "USER",
  ROLE: "ROLE",
  CATEGORY: "CATEGORY",
  SUPPLIER: "SUPPLIER",
  PRODUCT: "PRODUCT",
  CUSTOMER: "CUSTOMER",
  ORDER: "ORDER",
  ORDER_DETAIL: "ORDER_DETAIL",
  PAYMENT: "PAYMENT",
  STOCK_TRANSACTION: "STOCK_TRANSACTION",
  WARRANTY: "WARRANTY",
} as const;