"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "vi" | "en";

type Dictionary = Record<string, string>;

type TranslateParams = Record<string, string | number>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, params?: TranslateParams) => string;
};

const vi: Dictionary = {
  "app.title": "Homex POS",
  "app.subtitle": "Đồ gia dụng",
  "app.loadingAuth": "Đang kiểm tra đăng nhập",

  "language.vi": "VI",
  "language.en": "EN",
  "language.switchToEnglish": "Chuyển sang tiếng Anh",
  "language.switchToVietnamese": "Chuyển sang tiếng Việt",

  "topbar.greeting": "Xin chào,",
  "topbar.logout": "Đăng xuất",
  "topbar.collapseSidebar": "Thu gọn sidebar",
  "topbar.expandSidebar": "Mở rộng sidebar",
  "topbar.closeMenu": "Đóng menu",

  "nav.dashboard": "Tổng quan",
  "nav.groupOverview": "Tổng quan",
  "nav.groupSales": "Bán hàng",
  "nav.groupInventory": "Kho hàng",
  "nav.groupOperations": "Vận hành",
  "nav.groupAdmin": "Quản trị",
  "nav.groupLookup": "Tra cứu",
  "nav.pos": "Bán hàng POS",
  "nav.invoices": "Hóa đơn",
  "nav.orders": "Đơn hàng",
  "nav.products": "Sản phẩm",
  "nav.categories": "Danh mục",
  "nav.suppliers": "Nhà cung cấp",
  "nav.customers": "Khách hàng",
  "nav.inventory": "Kho hàng",
  "nav.warranties": "Bảo hành",
  "nav.payments": "Thanh toán",
  "nav.reports": "Báo cáo",
  "nav.employees": "Nhân viên",
  "nav.users": "Người dùng",
  "nav.auditLogs": "Lịch sử hệ thống",
  "nav.promotions": "Khuyến mãi",

  "common.actions": "Thao tác",
  "common.add": "Thêm",
  "common.addNew": "Thêm mới",
  "common.adjust": "Điều chỉnh",
  "common.all": "Tất cả",
  "common.allCategories": "Tất cả danh mục",
  "common.allMethods": "Tất cả phương thức",
  "common.allRoles": "Tất cả vai trò",
  "common.allStatus": "Tất cả trạng thái",
  "common.allTypes": "Tất cả loại",
  "common.back": "Quay lại",
  "common.cancel": "Hủy bỏ",
  "common.checkout": "Thanh toán",
  "common.choose": "Chọn",
  "common.chooseCategory": "Chọn danh mục",
  "common.chooseCustomer": "Chọn khách hàng",
  "common.chooseProduct": "Chọn sản phẩm",
  "common.chooseSupplier": "Chọn nhà cung cấp",
  "common.close": "Đóng",
  "common.code": "Mã",
  "common.confirm": "Xác nhận",
  "common.createdAt": "Ngày tạo",
  "common.create": "Tạo",
  "common.createNew": "Tạo mới",
  "common.delete": "Xóa",
  "common.detail": "Chi tiết",
  "common.email": "Email",
  "common.expire": "Hết hạn",
  "common.filter": "Lọc",
  "common.hide": "Ẩn",
  "common.id": "Mã ID",
  "common.image": "Ảnh",
  "common.name": "Tên",
  "common.next": "Sau",
  "common.no": "STT",
  "common.note": "Ghi chú",
  "common.order": "Đơn hàng",
  "common.phone": "Số điện thoại",
  "common.previous": "Trước",
  "common.restore": "Khôi phục",
  "common.role": "Vai trò",
  "common.save": "Lưu",
  "common.saveChanges": "Lưu thay đổi",
  "common.search": "Tìm kiếm",
  "common.show": "Hiện",
  "common.status": "Trạng thái",
  "common.update": "Cập nhật",
  "common.updatedAt": "Cập nhật",
  "common.view": "Xem",
  "common.yes": "Có",
  "common.notAvailable": "Không có",

  "message.loading": "Đang tải dữ liệu",
  "message.errorTitle": "Có lỗi xảy ra",
  "message.empty": "Chưa có dữ liệu",
  "message.saved": "Lưu dữ liệu thành công",
  "message.created": "Tạo dữ liệu thành công",
  "message.updated": "Cập nhật dữ liệu thành công",
  "message.deleted": "Xóa mềm thành công",
  "message.restored": "Khôi phục thành công",
  "message.noProducts": "Không tìm thấy sản phẩm",
  "message.emptyCart": "Giỏ hàng đang trống",
  "message.noLowStock": "Không có sản phẩm tồn thấp",
  "message.noInventoryTransactions": "Chưa có giao dịch kho",

  "pagination.info": "Trang {page}/{totalPages} · Tổng {totalItems} dòng",

  "status.ACTIVE": "Hoạt động",
  "status.INACTIVE": "Ngừng/Khoá",
  "status.DRAFT": "Nháp",
  "status.COMPLETED": "Hoàn tất",
  "status.CANCELLED": "Đã hủy",
  "status.PAID": "Đã thanh toán",
  "status.PENDING": "Chờ xử lý",
  "status.FAILED": "Thất bại",
  "status.REFUNDED": "Hoàn tiền",
  "status.EXPIRED": "Hết hạn",
  "status.IMPORT": "Nhập kho",
  "status.SALE": "Bán hàng",
  "status.ADJUSTMENT": "Điều chỉnh",
  "status.RESTORE": "Hoàn kho",
  "status.SUCCESS": "Thành công",
  "status.LOCKED": "Đã khóa",
  "status.DELETED": "Đã xóa",

  "paymentMethod.CASH": "Tiền mặt",
  "paymentMethod.CARD": "Quẹt thẻ",
  "paymentMethod.TRANSFER": "Chuyển khoản QR",
  "paymentMethod.BANK_TRANSFER": "Chuyển khoản QR",
  "paymentMethod.WALLET": "Ví điện tử",

  "role.ADMIN": "Quản trị viên",
  "role.CASHIER": "Thu ngân",

  "toast.success": "Thành công",
  "toast.error": "Có lỗi xảy ra",
  "toast.pos.emptyCart": "Vui lòng chọn sản phẩm trước khi thanh toán",
  "toast.pos.draftCreated": "Tạo đơn hàng nháp thành công",
  "toast.pos.draftUpdated": "Cập nhật đơn hàng nháp thành công",
  "toast.pos.checkoutSuccess": "Thanh toán hóa đơn thành công",
  "toast.pos.checkoutRequireDraft": "Vui lòng tạo bản nháp trước khi thanh toán",
  "toast.pos.customerCreated": "Tạo nhanh khách hàng thành công",
  "toast.pos.resumeDraftSuccess": "Đã nạp lại đơn nháp {code}. Bạn có thể chỉnh số lượng và thanh toán tiếp.",
  "toast.pos.resumeDraftInvalid": "Đơn hàng này không còn ở trạng thái nháp nên không thể tiếp tục thanh toán.",
  "toast.pos.cancelDraftSuccess": "Đã hủy đơn hàng thành công!",

  "login.title": "Homex POS",
  "login.description": "Đăng nhập hệ thống quản lý bán hàng đồ gia dụng",
  "login.email": "Email",
  "login.identifier": "Mã nhân viên hoặc email",
  "login.identifierRequired": "Vui lòng nhập mã nhân viên hoặc email",
  "login.password": "Mật khẩu",
  "login.passwordRequired": "Vui lòng nhập mật khẩu",
  "login.passwordPlaceholder": "Nhập mật khẩu",
  "login.submit": "Đăng nhập",
  "login.submitting": "Đang đăng nhập",
  "login.failed": "Đăng nhập thất bại",
  "login.info": "Thông báo",
  "login.expired": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  "login.demoTitle": "Tài khoản demo từ seed backend:",
  "login.demoAdmin": "Quản trị viên: NV0001 / 123456",
  "login.demoCashier": "Thu ngân: NV0002 / 123456",
  "login.footer": "© 2026 Homex POS - Hệ thống quản lý bán hàng",

  "dashboard.adminTitle": "Tổng quan quản trị",
  "dashboard.adminDescription": "Tổng quan doanh thu, đơn hàng, tồn kho, bảo hành và xu hướng bán hàng.",
  "dashboard.cashierTitle": "Tổng quan thu ngân",
  "dashboard.cashierDescription": "Bạn có thể bán hàng tại quầy, xem đơn hàng, khách hàng và tra cứu bảo hành.",
  "dashboard.readyToSell": "Sẵn sàng bán hàng",
  "dashboard.trackOrders": "Theo dõi giao dịch",
  "dashboard.quickWarranty": "Tra cứu nhanh",
  "dashboard.netRevenue": "Doanh thu ròng",
  "dashboard.grossRevenue": "Doanh thu gộp",
  "dashboard.completedOrders": "Đơn hoàn tất",
  "dashboard.draftOrders": "Đơn nháp",
  "dashboard.customers": "Khách hàng",
  "dashboard.activeProducts": "Sản phẩm đang bán",
  "dashboard.lowStock": "Sắp hết hàng",
  "dashboard.activeWarranties": "Bảo hành đang hiệu lực",
  "dashboard.revenue7Days": "Doanh thu 7 ngày",
  "dashboard.topProducts": "Top sản phẩm bán chạy",
  "dashboard.revenue": "Doanh thu",
  "dashboard.quantity": "Số lượng",

  "sidebar.collapse": "Thu gọn sidebar",
  "sidebar.expand": "Mở rộng sidebar",

  "categories.title": "Danh mục",
  "categories.description": "Quản lý danh mục sản phẩm, tìm kiếm, phân trang, xóa mềm và khôi phục.",
  "categories.add": "Thêm danh mục",
  "categories.updateTitle": "Cập nhật danh mục",
  "categories.createTitle": "Thêm danh mục",
  "categories.name": "Tên danh mục",
  "categories.descriptionField": "Mô tả",
  "categories.searchPlaceholder": "Tìm theo tên/mô tả",
  "categories.deleteConfirm": "Xóa mềm danh mục \"{name}\"?",
  "categories.restoreConfirm": "Khôi phục danh mục \"{name}\"?",

  "suppliers.title": "Nhà cung cấp",
  "suppliers.description": "Quản lý nhà cung cấp, tìm kiếm, phân trang, xóa mềm và khôi phục.",
  "suppliers.add": "Thêm nhà cung cấp",
  "suppliers.updateTitle": "Cập nhật nhà cung cấp",
  "suppliers.createTitle": "Thêm nhà cung cấp",
  "suppliers.name": "Tên nhà cung cấp",
  "suppliers.phone": "Số điện thoại",
  "suppliers.address": "Địa chỉ",
  "suppliers.searchPlaceholder": "Tìm theo tên/sđt/email/địa chỉ",
  "suppliers.deleteConfirm": "Xóa mềm nhà cung cấp \"{name}\"?",
  "suppliers.restoreConfirm": "Khôi phục nhà cung cấp \"{name}\"?",

  "customers.title": "Khách hàng",
  "customers.description": "Thu ngân được xem, tìm kiếm và tạo khách hàng. ADMIN được sửa, xóa mềm và khôi phục.",
  "customers.add": "Thêm khách hàng",
  "customers.quickAdd": "Tạo nhanh khách hàng",
  "customers.updateTitle": "Cập nhật khách hàng",
  "customers.createTitle": "Thêm khách hàng",
  "customers.fullName": "Họ tên",
  "customers.points": "Điểm",
  "customers.tier": "Hạng",
  "customers.address": "Địa chỉ",
  "customers.searchPlaceholder": "Tìm theo tên/sđt/email/địa chỉ",
  "customers.deleteConfirm": "Xóa mềm khách hàng \"{name}\"?",
  "customers.restoreConfirm": "Khôi phục khách hàng \"{name}\"?",
  "customers.retail": "Khách lẻ",
  "customers.createdQuick": "Tạo nhanh khách hàng thành công",
  "customerTier.SILVER": "Bạc",
  "customerTier.GOLD": "Vàng",
  "customerTier.DIAMOND": "Kim cương",

  "products.title": "Sản phẩm",
  "products.description": "Quản lý sản phẩm, lọc danh mục/nhà cung cấp, cảnh báo tồn thấp, xóa mềm và khôi phục.",
  "products.add": "Thêm sản phẩm",
  "products.bulkAdd": "Nhập dữ liệu mẫu",
  "products.bulkRunning": "Đang nhập mẫu",
  "products.bulkResult": "Đã tạo {created} sản phẩm, bỏ qua/lỗi {failed} sản phẩm.",
  "products.importFile": "Nhập JSON/CSV",
  "products.importFileEmpty": "File không có dữ liệu sản phẩm hợp lệ.",
  "products.deleteSelected": "Xóa {count} mục đã chọn",
  "products.bulkDeleteConfirm": "Xóa mềm {count} sản phẩm đã chọn?",
  "products.bulkDeleteResult": "Đã xóa mềm {deleted} sản phẩm, lỗi {failed} sản phẩm.",
  "products.deleteAll": "Xóa tất cả sản phẩm",
  "products.deleteAllConfirmTitle": "Xác nhận xóa tất cả sản phẩm",
  "products.deleteAllConfirmDescription": "Hành động này sẽ xóa mềm toàn bộ sản phẩm theo bộ lọc hiện tại. Bạn có chắc chắn muốn tiếp tục?",
  "products.deleteAllResult": "Đã xóa mềm {deleted} sản phẩm, lỗi {failed} sản phẩm.",
  "products.cancelDanger": "Không xóa",
  "products.selectAll": "Chọn tất cả sản phẩm đang hiển thị",
  "products.selectProduct": "Chọn sản phẩm {sku}",
  "products.updateTitle": "Cập nhật sản phẩm",
  "products.createTitle": "Thêm sản phẩm",
  "products.searchPlaceholder": "Tìm SKU/tên/mô tả/QR",
  "products.sku": "SKU",
  "products.product": "Sản phẩm",
  "products.name": "Tên sản phẩm",
  "products.category": "Danh mục",
  "products.supplier": "Nhà cung cấp",
  "products.supplierShort": "NCC",
  "products.costPrice": "Giá nhập",
  "products.salePrice": "Giá bán",
  "products.stock": "Tồn",
  "products.stockQuantity": "Tồn kho",
  "products.minStock": "Tồn tối thiểu",
  "products.warrantyMonths": "Bảo hành tháng",
  "products.qrCode": "Mã QR",
  "products.openQr": "Mở mã QR",
  "products.printQr": "In mã",
  "products.qrPlaceholder": "Bỏ trống để tự dùng SKU",
  "products.qrDialogTitle": "Mã QR sản phẩm",
  "products.qrDialogDescription": "Mã QR được tạo từ SKU hoặc mã QR của sản phẩm để demo quét tại quầy bán hàng.",
  "products.lowShort": "Thấp",
  "products.imageUrl": "URL ảnh",
  "products.descriptionField": "Mô tả",
  "products.lowStockOnly": "Chỉ tồn thấp",
  "products.months": "tháng",
  "products.updatedAt": "Cập nhật: {date}",
  "products.deleteConfirm": "Xóa mềm sản phẩm \"{name}\"?",
  "products.restoreConfirm": "Khôi phục sản phẩm \"{name}\"?",
  "products.needOptions": "Cần có ít nhất 1 danh mục và 1 nhà cung cấp đang hoạt động trước khi nhập dữ liệu mẫu.",
  "products.importGuideTitle": "Cấu trúc file JSON/CSV chuẩn",
  "products.importGuideDescription": "Xem đúng cấu trúc dữ liệu trước khi tải file lên. Các trường categoryId và supplierId phải là mã ID đang tồn tại trong hệ thống.",
  "products.jsonExample": "Ví dụ JSON",
  "products.csvExample": "Ví dụ CSV",
  "products.copyStructure": "Copy cấu trúc mẫu",
  "products.proceedUpload": "Tiến hành tải file lên",
  "products.structureCopied": "Đã copy cấu trúc mẫu vào clipboard.",

  "orders.title": "Đơn hàng",
  "orders.description": "Xem danh sách, chi tiết đơn hàng, thanh toán và bảo hành; quản trị viên được hủy đơn.",
  "orders.searchPlaceholder": "Tìm mã đơn, khách hàng, thu ngân",
  "orders.orderCode": "Mã đơn",
  "orders.customer": "Khách hàng",
  "orders.cashier": "Thu ngân",
  "orders.total": "Tổng tiền",
  "orders.createdAt": "Ngày tạo",
  "orders.cancelConfirm": "Hủy đơn {code}? Nếu đơn đã hoàn tất, backend sẽ restore tồn kho.",
  "orders.detailTitle": "Chi tiết {code}",
  "orders.items": "Sản phẩm trong đơn",
  "orders.payment": "Thanh toán",
  "orders.warranty": "Bảo hành",
  "orders.noPayment": "Chưa có thanh toán",
  "orders.continuePayment": "Tiếp tục thanh toán",
  "orders.printInvoice": "In hóa đơn",
  "orders.cancelOrder": "Hủy đơn hàng",
  "orders.cancelSuccess": "Đã hủy đơn hàng {code} thành công.",
  "orders.onlyDraftCanContinue": "Chỉ đơn hàng nháp mới được tiếp tục thanh toán.",
  "orders.unitPrice": "Đơn giá",
  "orders.lineTotal": "Thành tiền",
  "orders.noWarranty": "Không có phiếu bảo hành liên quan.",

  "inventory.title": "Kho hàng",
  "inventory.description": "Theo dõi tồn thấp, nhập kho, điều chỉnh kho và lịch sử giao dịch kho.",
  "inventory.importStock": "Nhập kho",
  "inventory.adjustStock": "Điều chỉnh tồn",
  "inventory.product": "Sản phẩm",
  "inventory.importQuantity": "Số lượng nhập",
  "inventory.newQuantity": "Tồn kho mới",
  "inventory.note": "Ghi chú",
  "inventory.lowStockTitle": "Sản phẩm sắp hết hàng",
  "inventory.minStock": "Tối thiểu",
  "inventory.searchPlaceholder": "Tìm sản phẩm/giao dịch kho",
  "inventory.filterTransactions": "Lọc giao dịch",
  "inventory.transactionHistory": "Lịch sử giao dịch kho",
  "inventory.type": "Loại",
  "inventory.quantity": "Số lượng",
  "inventory.operator": "Người thao tác",
  "inventory.importSuccess": "Nhập kho thành công",
  "inventory.adjustSuccess": "Điều chỉnh tồn kho thành công",
  "inventory.comboboxPlaceholder": "Gõ SKU hoặc tên sản phẩm...",
  "inventory.comboboxEmpty": "Không tìm thấy sản phẩm",

  "pos.title": "Bán hàng POS",
  "pos.description": "Tìm sản phẩm, thêm vào giỏ hàng, tạo bản nháp, cập nhật bản nháp và thanh toán.",
  "pos.searchProduct": "Tìm SKU, tên sản phẩm, mô tả hoặc mã QR...",
  "pos.allProducts": "Tất cả",
  "pos.addToCart": "Thêm vào giỏ",
  "pos.outOfStock": "Hết hàng",
  "pos.cart": "Giỏ hàng",
  "pos.findCustomer": "Tìm khách hàng",
  "pos.customerPlaceholder": "Tên/SĐT khách",
  "pos.find": "Tìm",
  "pos.paymentMethod": "Phương thức thanh toán",
  "pos.createDraft": "Tạo bản nháp",
  "pos.updateDraft": "Cập nhật",
  "pos.checkout": "Thanh toán",
  "pos.subtotal": "Tạm tính",
  "pos.discount": "Giảm giá/Chiết khấu",
  "pos.totalPayable": "Tổng tiền cần trả",
  "pos.draftCode": "Đơn nháp: {code}",
  "pos.draftCreated": "Tạo đơn hàng nháp thành công",
  "pos.draftUpdated": "Cập nhật đơn hàng nháp thành công",
  "pos.checkoutSuccess": "Thanh toán hóa đơn thành công",
  "pos.noCart": "Vui lòng chọn sản phẩm trước khi thanh toán",
  "pos.quickCustomer": "Tạo nhanh khách hàng tại quầy",
  "pos.quickCustomerDescription": "Thông tin khách hàng mới sẽ được lưu vào hệ thống và chọn ngay cho đơn bán hàng hiện tại.",
  "pos.emptyCartHint": "Chọn sản phẩm bên trái để thêm vào giỏ hàng.",
  "pos.discountInputPlaceholder": "Nhập số tiền hoặc %, ví dụ 50.000 hoặc 10%",
  "pos.manualDiscountType": "Loại",
  "pos.discountAmount": "Tiền",
  "pos.discountPercent": "%",
  "pos.manualDiscountPlaceholderAmount": "50.000",
  "pos.manualDiscountPlaceholderPercent": "10",
  "pos.invalidDiscountAmount": "Số tiền chiết khấu không hợp lệ.",
  "pos.invalidDiscountPercent": "Phần trăm chiết khấu phải từ 1 đến 100.",
  "pos.applyDiscount": "Áp dụng",
  "pos.discountEmpty": "Vui lòng nhập mã giảm giá hoặc số tiền chiết khấu.",
  "pos.discountNeedCart": "Vui lòng chọn sản phẩm trước khi áp dụng giảm giá.",
  "pos.discountApplied": "Đã áp dụng giảm giá {amount}.",
  "pos.noVoucher": "Không dùng Voucher",
  "pos.manualDiscount": "Chiết khấu đơn",
  "pos.voucherHelp": "Chọn mã giảm giá phù hợp với đơn hàng",
  "pos.manualDiscountHelp": "Giảm thủ công cho toàn bộ hóa đơn",
  "toast.pos.voucherApplied": "Đã áp dụng mã giảm giá {code}.",
  "toast.pos.voucherAppliedWithAmount": "Đã áp dụng mã giảm giá {code}, giảm {amount}.",
  "toast.pos.manualDiscountAmountApplied": "Đã áp dụng mức chiết khấu {amount}.",
  "toast.pos.manualDiscountPercentApplied": "Đã áp dụng mức chiết khấu {percent}%.",
  "pos.voucher": "Voucher",
  "pos.apply": "Áp dụng",
  "pos.discountPercentInvalid": "Phần trăm giảm giá phải lớn hơn 0 và không vượt quá 100%.",
  "pos.discountAmountInvalid": "Số tiền giảm giá không hợp lệ.",
  "pos.voucherInvalid": "Mã giảm giá không hợp lệ hoặc không đủ điều kiện áp dụng.",
  "pos.decreaseQuantity": "Giảm số lượng",
  "pos.increaseQuantity": "Tăng số lượng",
  "pos.processingDraft": "Đang xử lý đơn nháp",
  "pos.cancelOrder": "Hủy đơn",
  "pos.cancelDraftTitle": "Hủy đơn hàng nháp",
  "pos.cancelDraftDescription": "Bạn có chắc chắn muốn hủy đơn hàng nháp này không?",
  "pos.cancelDraftWarning": "Thao tác này sẽ chuyển đơn nháp sang trạng thái Đã hủy, xóa giỏ hàng hiện tại và đưa màn hình POS về trạng thái tạo đơn mới.",
  "pos.keepDraft": "Không hủy",
  "pos.confirmCancelDraft": "Xác nhận hủy đơn",

  "warranties.title": "Bảo hành",
  "warranties.description": "Danh sách, tra cứu mã bảo hành, chi tiết và thao tác ADMIN.",
  "warranties.createManual": "Tạo thủ công",
  "warranties.searchPlaceholder": "Tìm mã BH, khách, SĐT",
  "warranties.warrantyCode": "Mã BH",
  "warranties.customer": "Khách hàng",
  "warranties.product": "Sản phẩm",
  "warranties.startDate": "Bắt đầu",
  "warranties.endDate": "Kết thúc",
  "warranties.lookupTitle": "Tra cứu theo mã",
  "warranties.lookupPlaceholder": "Nhập mã bảo hành",
  "warranties.lookup": "Tra cứu",
  "warranties.detailTitle": "Chi tiết {code}",
  "warranties.order": "Đơn hàng",
  "warranties.productValue": "Giá trị dòng hàng",
  "warranties.cancelConfirm": "Hủy bảo hành {code}?",
  "warranties.restoreConfirm": "Khôi phục bảo hành {code}?",
  "warranties.expireConfirm": "Chuyển bảo hành {code} sang hết hạn?",
  "warranties.orderCode": "Mã hóa đơn",
  "warranties.orderCodePlaceholder": "Nhập mã hóa đơn, ví dụ: HD202606071931388250",
  "warranties.orderCodeHint": "Nhập mã hóa đơn đã hoàn tất để hệ thống lấy danh sách sản phẩm trong đơn.",
  "warranties.findOrder": "Tìm đơn hàng",
  "warranties.orderLoaded": "Đã tải đơn hàng {code}.",
  "warranties.orderNotFound": "Không tìm thấy đơn hàng phù hợp với mã đã nhập.",
  "warranties.orderCodeRequired": "Vui lòng nhập mã hóa đơn trước khi tìm kiếm.",
  "warranties.searchOrderFirst": "Vui lòng tìm đơn hàng trước",
  "warranties.chooseProductFromOrder": "Chọn sản phẩm trong hóa đơn",
  "warranties.chooseProductPlaceholder": "Chọn sản phẩm cần kích hoạt bảo hành",
  "warranties.chooseOrderProduct": "Vui lòng chọn sản phẩm trong hóa đơn để tạo bảo hành.",
  "warranties.hiddenOrderDetailHint": "Hệ thống tự lấy mã dòng đơn hàng ẩn từ sản phẩm đã chọn, người dùng không cần nhập mã dòng cơ sở dữ liệu.",
  "warranties.manualCreated": "Tạo bảo hành thủ công thành công",

  "payments.title": "Thanh toán",
  "payments.description": "Quản lý dòng tiền, kênh nhận tiền, chứng từ đối soát và hoàn tiền giao dịch.",
  "payments.searchPlaceholder": "Nhập mã giao dịch hoặc mã hóa đơn để tìm...",
  "payments.id": "Mã ID",
  "payments.order": "Đơn hàng",
  "payments.method": "Phương thức",
  "payments.amount": "Số tiền",
  "payments.paidAt": "Ngày thanh toán",
  "payments.findByOrder": "Tìm kiếm theo mã đơn hàng",
  "payments.orderIdPlaceholder": "Nhập mã đơn hàng...",
  "payments.noPaymentSelected": "Chưa chọn thanh toán",
  "payments.detailTitle": "Chi tiết thanh toán #{id}",
  "payments.refund": "Hoàn tiền",
  "payments.refundConfirm": "Bạn có chắc chắn muốn hoàn tiền giao dịch {code} không?",
  "payments.transactionId": "Mã giao dịch thanh toán",
  "payments.linkedOrderCode": "Mã hóa đơn liên kết",
  "payments.amountPaid": "Số tiền thanh toán",
  "payments.viewVoucher": "Xem chứng từ",
  "payments.refundTransaction": "Hoàn tiền giao dịch",
  "payments.refundSuccess": "Đã hoàn tiền giao dịch {code} thành công.",
  "payments.voucherTitle": "Chứng từ thanh toán {code}",
  "payments.reconcileCode": "Mã đối soát",
  "payments.cashflowStatus": "Trạng thái dòng tiền",
  "payments.internalOrderId": "Mã đơn nội bộ",

  "reports.title": "Báo cáo",
  "reports.description": "Tổng hợp doanh thu, top sản phẩm, tồn thấp và khách hàng.",
  "reports.fromDate": "Từ ngày",
  "reports.toDate": "Đến ngày",
  "reports.apply": "Áp dụng",
  "reports.summary": "Tổng quan",
  "reports.revenueChart": "Doanh thu theo ngày",
  "reports.profitChart": "Doanh thu, vốn và lợi nhuận",
  "reports.topProducts": "Sản phẩm bán chạy",
  "reports.topCustomers": "Khách hàng mua nhiều",
  "reports.lowStock": "Sản phẩm tồn thấp",
  "reports.customers": "Khách hàng",
  "reports.quantity": "Số lượng",
  "reports.revenue": "Doanh thu",
  "reports.cogs": "Giá vốn",
  "reports.netProfit": "Lợi nhuận ròng",
  "reports.totalSpent": "Tổng chi",
  "reports.totalOrders": "Số đơn",
  "reports.latestOrder": "Đơn gần nhất",
  "reports.noProfitData": "Chưa có dữ liệu doanh thu, giá vốn và lợi nhuận trong khoảng thời gian đã chọn.",
  "reports.noTopProductData": "Chưa có dữ liệu sản phẩm bán chạy trong khoảng thời gian đã chọn.",

  "users.title": "Nhân viên",
  "users.description": "Quản trị viên tạo mã đăng nhập, cập nhật, khóa, khôi phục và đổi mật khẩu nhân viên.",
  "users.add": "Thêm nhân viên",
  "users.searchPlaceholder": "Tìm tên, mã nhân viên, email, số điện thoại",
  "users.employeeCode": "Mã nhân viên",
  "users.employeeCodeAuto": "Tự tạo nếu bỏ trống",
  "users.emailOptional": "Email liên hệ (không bắt buộc)",
  "users.fullName": "Họ tên",
  "users.password": "Mật khẩu",
  "users.newPassword": "Mật khẩu mới",
  "users.createTitle": "Tạo nhân viên",
  "users.updateTitle": "Cập nhật {email}",
  "users.changePasswordTitle": "Đổi mật khẩu {email}",
  "users.changePassword": "Đổi mật khẩu",
  "users.lock": "Khóa",
  "users.unlock": "Khôi phục",
  "users.createSuccess": "Tạo nhân viên thành công",
  "users.updateSuccess": "Cập nhật nhân viên thành công",
  "users.passwordSuccess": "Đổi mật khẩu thành công. Mật khẩu mới: {password}",
  "users.lockConfirm": "Khóa tài khoản {email}?",
  "users.restoreConfirm": "Khôi phục tài khoản {email}?",
  "users.lastLoginAt": "Lần đăng nhập",
  "users.validationRequired": "Vui lòng nhập thông tin bắt buộc",
  "users.validationEmail": "Email không hợp lệ",
  "users.validationPassword": "Mật khẩu tối thiểu 6 ký tự",

  "audit.title": "Lịch sử hệ thống",
  "audit.description": "Theo dõi nhật ký thao tác hệ thống, lọc theo hành động, đối tượng, người dùng và khoảng ngày.",
  "audit.searchPlaceholder": "Tìm hành động, đối tượng, mô tả...",
  "audit.action": "Hành động",
  "audit.entityType": "Loại đối tượng",
  "audit.entityId": "Mã đối tượng",
  "audit.userIdFilter": "Mã đối tượng",
  "audit.user": "Người dùng",
  "audit.descriptionField": "Mô tả",
  "audit.detailTitle": "Chi tiết nhật ký #{id}",
  "audit.oldValue": "Giá trị cũ",
  "audit.newValue": "Giá trị mới",

  "promotions.title": "Khuyến mãi",
  "promotions.description": "Quản lý mã giảm giá, điều kiện đơn hàng tối thiểu, số lượt dùng và ngày hết hạn.",
  "promotions.add": "Thêm mã",
  "promotions.searchPlaceholder": "Tìm mã giảm giá...",
  "promotions.code": "Mã giảm giá",
  "promotions.discountType": "Hình thức giảm giá",
  "promotions.discountValue": "Mức giảm",
  "promotions.minOrderAmount": "Đơn hàng tối thiểu",
  "promotions.amountType": "Số tiền cố định",
  "promotions.percentType": "Phần trăm hóa đơn",
  "promotions.usedUp": "Hết lượt",
  "promotions.createTitle": "Tạo mã giảm giá",
  "promotions.editTitle": "Cập nhật mã giảm giá",
  "promotions.formDescription": "Nhập thông tin mã giảm giá để áp dụng tại màn hình POS.",
  "promotions.usageLimit": "Số lượt sử dụng",
  "promotions.unlimited": "Không giới hạn",
  "promotions.expiredAt": "Ngày hết hạn",
  "promotions.created": "Tạo mã giảm giá thành công.",
  "promotions.updated": "Cập nhật mã giảm giá thành công.",
  "promotions.deleted": "Xóa mã giảm giá thành công.",
  "promotions.deleteConfirm": "Xóa mã giảm giá {code}?",
  "promotions.formInvalid": "Vui lòng nhập đầy đủ mã, mức giảm và ngày hết hạn.",
  "promotions.quantity": "Số lượng",
  "promotions.remainingQuantity": "Số lượng còn lại",
  "promotions.codePlaceholder": "Ví dụ: HOMEX50K",
  "promotions.discountValueMoneyPlaceholder": "Ví dụ: 50.000 đ",
  "promotions.discountValuePercentPlaceholder": "Ví dụ: 10%",
  "promotions.minOrderAmountPlaceholder": "Ví dụ: 200.000 đ",
  "promotions.percentInvalid": "Phần trăm giảm giá phải lớn hơn 0 và không vượt quá 100%.",
  "promotions.apiNotMounted": "API khuyến mãi chưa được kết nối trong backend.",
  "promotions.backendNotConfigured": "Backend khuyến mãi chưa cấu hình đủ model hoặc migration.",

  "auth.checkingPermission": "Đang kiểm tra quyền truy cập",
  "auth.noPermission": "Không có quyền truy cập",
  "auth.noPermissionDescription": "Chức năng này chỉ dành cho vai trò được cấp quyền.",
  "auth.currentNoPermission": "Tài khoản hiện tại không được phép sử dụng chức năng này.",
  "auth.backDashboard": "Quay về tổng quan",

  "home.redirecting": "Đang chuyển trang",
};

const en: Dictionary = {
  "app.title": "Homex POS",
  "app.subtitle": "Home appliances",
  "app.loadingAuth": "Checking authentication",

  "language.vi": "VI",
  "language.en": "EN",
  "language.switchToEnglish": "Switch to English",
  "language.switchToVietnamese": "Switch to Vietnamese",

  "topbar.greeting": "Hello,",
  "topbar.logout": "Logout",
  "topbar.collapseSidebar": "Collapse sidebar",
  "topbar.expandSidebar": "Expand sidebar",
  "topbar.closeMenu": "Close menu",

  "nav.dashboard": "Dashboard",
  "nav.groupOverview": "Overview",
  "nav.groupSales": "Sales",
  "nav.groupInventory": "Inventory",
  "nav.groupOperations": "Operations",
  "nav.groupAdmin": "Admin",
  "nav.groupLookup": "Lookup",
  "nav.pos": "POS Sale",
  "nav.invoices": "Invoices",
  "nav.orders": "Orders",
  "nav.products": "Products",
  "nav.categories": "Categories",
  "nav.suppliers": "Suppliers",
  "nav.customers": "Customers",
  "nav.inventory": "Inventory",
  "nav.warranties": "Warranties",
  "nav.payments": "Payments",
  "nav.reports": "Reports",
  "nav.employees": "Employees",
  "nav.users": "Users",
  "nav.auditLogs": "Audit Logs",
  "nav.promotions": "Promotions",

  "common.actions": "Actions",
  "common.add": "Add",
  "common.addNew": "Add new",
  "common.adjust": "Adjust",
  "common.all": "All",
  "common.allCategories": "All categories",
  "common.allMethods": "All methods",
  "common.allRoles": "All roles",
  "common.allStatus": "All statuses",
  "common.allTypes": "All types",
  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.checkout": "Checkout",
  "common.choose": "Choose",
  "common.chooseCategory": "Choose category",
  "common.chooseCustomer": "Choose customer",
  "common.chooseProduct": "Choose product",
  "common.chooseSupplier": "Choose supplier",
  "common.close": "Close",
  "common.code": "Code",
  "common.confirm": "Confirm",
  "common.createdAt": "Created At",
  "common.create": "Create",
  "common.createNew": "Create new",
  "common.delete": "Delete",
  "common.detail": "Detail",
  "common.email": "Email",
  "common.expire": "Expire",
  "common.filter": "Filter",
  "common.hide": "Hide",
  "common.id": "ID",
  "common.image": "Image",
  "common.name": "Name",
  "common.next": "Next",
  "common.no": "No.",
  "common.note": "Note",
  "common.order": "Order",
  "common.phone": "Phone",
  "common.previous": "Previous",
  "common.restore": "Restore",
  "common.role": "Role",
  "common.save": "Save",
  "common.saveChanges": "Save changes",
  "common.search": "Search",
  "common.show": "Show",
  "common.status": "Status",
  "common.update": "Update",
  "common.updatedAt": "Updated at",
  "common.view": "View",
  "common.yes": "Yes",
  "common.notAvailable": "N/A",

  "message.loading": "Loading data",
  "message.errorTitle": "Something went wrong",
  "message.empty": "No data available",
  "message.saved": "Data saved successfully",
  "message.created": "Data created successfully",
  "message.updated": "Data updated successfully",
  "message.deleted": "Soft delete completed",
  "message.restored": "Restore completed",
  "message.noProducts": "No products found",
  "message.emptyCart": "Your cart is empty",
  "message.noLowStock": "No low-stock products",
  "message.noInventoryTransactions": "No inventory transactions yet",

  "pagination.info": "Page {page}/{totalPages} · Total {totalItems} rows",

  "status.ACTIVE": "Active",
  "status.INACTIVE": "Inactive/Locked",
  "status.DRAFT": "Draft",
  "status.COMPLETED": "Completed",
  "status.CANCELLED": "Cancelled",
  "status.PAID": "Paid",
  "status.PENDING": "Pending",
  "status.FAILED": "Failed",
  "status.REFUNDED": "Refunded",
  "status.EXPIRED": "Expired",
  "status.IMPORT": "Import",
  "status.SALE": "Sale",
  "status.ADJUSTMENT": "Adjustment",
  "status.RESTORE": "Stock restore",
  "status.SUCCESS": "Success",
  "status.LOCKED": "Locked",
  "status.DELETED": "Deleted",

  "paymentMethod.CASH": "Cash",
  "paymentMethod.CARD": "Card Swipe",
  "paymentMethod.TRANSFER": "QR Transfer",
  "paymentMethod.BANK_TRANSFER": "QR Transfer",
  "paymentMethod.WALLET": "E-Wallet",

  "role.ADMIN": "Administrator",
  "role.CASHIER": "Cashier",

  "toast.success": "Success",
  "toast.error": "Error",
  "toast.pos.emptyCart": "Please select products before checkout",
  "toast.pos.draftCreated": "Draft order created successfully",
  "toast.pos.draftUpdated": "Draft order updated successfully",
  "toast.pos.checkoutSuccess": "Order paid successfully",
  "toast.pos.checkoutRequireDraft": "Please create a draft order before checkout",
  "toast.pos.customerCreated": "Quick customer created successfully",
  "toast.pos.resumeDraftSuccess": "Draft order {code} has been restored. You can adjust quantities and continue checkout.",
  "toast.pos.resumeDraftInvalid": "This order is no longer a draft and cannot be resumed.",
  "toast.pos.cancelDraftSuccess": "Order cancelled successfully!",

  "login.title": "Homex POS",
  "login.description": "Log in to the home appliance POS management system",
  "login.email": "Email",
  "login.identifier": "Employee code or email",
  "login.identifierRequired": "Please enter employee code or email",
  "login.password": "Password",
  "login.passwordRequired": "Please enter password",
  "login.passwordPlaceholder": "Enter password",
  "login.submit": "Log in",
  "login.submitting": "Logging in",
  "login.failed": "Login failed",
  "login.info": "Notice",
  "login.expired": "Your session has expired. Please log in again.",
  "login.demoTitle": "Demo accounts from backend seed:",
  "login.demoAdmin": "Administrator: NV0001 / 123456",
  "login.demoCashier": "Cashier: NV0002 / 123456",
  "login.footer": "© 2026 Homex POS - Retail management system",

  "dashboard.adminTitle": "Admin Dashboard",
  "dashboard.adminDescription": "Overview of revenue, orders, inventory, warranties and sales trends.",
  "dashboard.cashierTitle": "Cashier Dashboard",
  "dashboard.cashierDescription": "You can sell through POS, view orders, products, customers, warranties and payments.",
  "dashboard.readyToSell": "Ready to sell",
  "dashboard.trackOrders": "Track transactions",
  "dashboard.quickWarranty": "Quick lookup",
  "dashboard.netRevenue": "Net revenue",
  "dashboard.grossRevenue": "Gross revenue",
  "dashboard.completedOrders": "Completed orders",
  "dashboard.draftOrders": "Draft orders",
  "dashboard.customers": "Customers",
  "dashboard.activeProducts": "Active products",
  "dashboard.lowStock": "Low stock",
  "dashboard.activeWarranties": "Active warranties",
  "dashboard.revenue7Days": "Revenue in 7 days",
  "dashboard.topProducts": "Top Selling Products",
  "dashboard.revenue": "Revenue",
  "dashboard.quantity": "Quantity",

  "sidebar.collapse": "Collapse sidebar",
  "sidebar.expand": "Expand sidebar",

  "categories.title": "Categories",
  "categories.description": "Manage product categories, search, pagination, soft delete and restore.",
  "categories.add": "Add category",
  "categories.updateTitle": "Update category",
  "categories.createTitle": "Add category",
  "categories.name": "Category name",
  "categories.descriptionField": "Description",
  "categories.searchPlaceholder": "Search by name/description",
  "categories.deleteConfirm": "Soft delete category \"{name}\"?",
  "categories.restoreConfirm": "Restore category \"{name}\"?",

  "suppliers.title": "Suppliers",
  "suppliers.description": "Manage suppliers, search, pagination, soft delete and restore.",
  "suppliers.add": "Add supplier",
  "suppliers.updateTitle": "Update supplier",
  "suppliers.createTitle": "Add supplier",
  "suppliers.name": "Supplier name",
  "suppliers.phone": "Phone",
  "suppliers.address": "Address",
  "suppliers.searchPlaceholder": "Search by name/phone/email/address",
  "suppliers.deleteConfirm": "Soft delete supplier \"{name}\"?",
  "suppliers.restoreConfirm": "Restore supplier \"{name}\"?",

  "customers.title": "Customers",
  "customers.description": "Cashiers can view, search and create customers. ADMIN can edit, soft delete and restore.",
  "customers.add": "Add customer",
  "customers.quickAdd": "Quick add customer",
  "customers.updateTitle": "Update customer",
  "customers.createTitle": "Add customer",
  "customers.fullName": "Full name",
  "customers.fullNamePlaceholder": "John Smith",
  "customers.phonePlaceholder": "0901234567",
  "customers.emailPlaceholder": "customer@example.com",
  "customers.addressPlaceholder": "House number, street, ward, district",
  "customers.notePlaceholder": "Additional note if needed",
  "customers.points": "Points",
  "customers.tier": "Tier",
  "customers.address": "Address",
  "customers.searchPlaceholder": "Search by name/phone/email/address",
  "customers.deleteConfirm": "Soft delete customer \"{name}\"?",
  "customers.restoreConfirm": "Restore customer \"{name}\"?",
  "customers.retail": "Walk-in customer",
  "customers.createdQuick": "Quick customer created successfully",
  "customerTier.SILVER": "Silver",
  "customerTier.GOLD": "Gold",
  "customerTier.DIAMOND": "Diamond",

  "products.title": "Products",
  "products.description": "Manage products, filter categories/suppliers, low-stock warnings, soft delete and restore.",
  "products.add": "Add product",
  "products.bulkAdd": "Import sample data",
  "products.bulkRunning": "Importing samples",
  "products.bulkResult": "Created {created} products, skipped/failed {failed} products.",
  "products.importFile": "Import JSON/CSV",
  "products.importFileEmpty": "The file does not contain valid product data.",
  "products.deleteSelected": "Delete {count} selected",
  "products.bulkDeleteConfirm": "Soft delete {count} selected products?",
  "products.bulkDeleteResult": "Soft deleted {deleted} products, failed {failed} products.",
  "products.deleteAll": "Delete all products",
  "products.deleteAllConfirmTitle": "Confirm deleting all products",
  "products.deleteAllConfirmDescription": "This action will soft delete every product that matches the current filters. Are you sure you want to continue?",
  "products.deleteAllResult": "Soft deleted {deleted} products, failed {failed} products.",
  "products.cancelDanger": "Do not delete",
  "products.selectAll": "Select all visible products",
  "products.selectProduct": "Select product {sku}",
  "products.updateTitle": "Update product",
  "products.createTitle": "Add product",
  "products.searchPlaceholder": "Search SKU/name/description/QR",
  "products.sku": "SKU",
  "products.product": "Product",
  "products.name": "Product name",
  "products.category": "Category",
  "products.supplier": "Supplier",
  "products.supplierShort": "Supplier",
  "products.costPrice": "Cost price",
  "products.salePrice": "Sale price",
  "products.stock": "Stock",
  "products.stockQuantity": "Stock quantity",
  "products.minStock": "Minimum stock",
  "products.warrantyMonths": "Warranty months",
  "products.qrCode": "QR Code",
  "products.openQr": "Open QR code",
  "products.printQr": "Print code",
  "products.qrPlaceholder": "Leave blank to use SKU",
  "products.qrDialogTitle": "Product QR code",
  "products.qrDialogDescription": "The QR code is rendered from product SKU or QR code for POS counter scanning demo.",
  "products.lowShort": "Low",
  "products.imageUrl": "Image URL",
  "products.descriptionField": "Description",
  "products.lowStockOnly": "Low stock only",
  "products.months": "months",
  "products.updatedAt": "Updated: {date}",
  "products.deleteConfirm": "Soft delete product \"{name}\"?",
  "products.restoreConfirm": "Restore product \"{name}\"?",
  "products.needOptions": "You need at least 1 active category and 1 active supplier before importing sample data.",
  "products.importGuideTitle": "Required JSON/CSV file structure",
  "products.importGuideDescription": "Review the expected data structure before uploading. categoryId and supplierId must be existing IDs in the system.",
  "products.jsonExample": "JSON example",
  "products.csvExample": "CSV example",
  "products.copyStructure": "Copy sample structure",
  "products.proceedUpload": "Proceed to upload file",
  "products.structureCopied": "Sample structure copied to clipboard.",

  "orders.title": "Orders",
  "orders.description": "View order list, details, payment, warranty; ADMIN can cancel orders.",
  "orders.searchPlaceholder": "Search order code, customer, cashier",
  "orders.orderCode": "Order code",
  "orders.customer": "Customer",
  "orders.cashier": "Cashier",
  "orders.total": "Total",
  "orders.createdAt": "Created at",
  "orders.cancelConfirm": "Cancel order {code}? If completed, backend will restore inventory.",
  "orders.detailTitle": "Details {code}",
  "orders.items": "Order items",
  "orders.payment": "Payment",
  "orders.warranty": "Warranty",
  "orders.noPayment": "No payment yet",
  "orders.continuePayment": "Continue Checkout",
  "orders.printInvoice": "Print Invoice",
  "orders.cancelOrder": "Cancel Order",
  "orders.cancelSuccess": "Order {code} cancelled successfully.",
  "orders.onlyDraftCanContinue": "Only draft orders can continue checkout.",
  "orders.unitPrice": "Unit Price",
  "orders.lineTotal": "Line Total",
  "orders.noWarranty": "No related warranty records.",

  "inventory.title": "Inventory",
  "inventory.description": "Track low stock, import stock, adjust stock and inventory transaction history.",
  "inventory.importStock": "Import stock",
  "inventory.adjustStock": "Adjust stock",
  "inventory.product": "Product",
  "inventory.importQuantity": "Import quantity",
  "inventory.newQuantity": "New stock quantity",
  "inventory.note": "Note",
  "inventory.lowStockTitle": "Low-stock products",
  "inventory.minStock": "Min stock",
  "inventory.searchPlaceholder": "Search products/inventory transactions",
  "inventory.filterTransactions": "Filter transactions",
  "inventory.transactionHistory": "Inventory transaction history",
  "inventory.type": "Type",
  "inventory.quantity": "Quantity",
  "inventory.operator": "Operator",
  "inventory.importSuccess": "Stock imported successfully",
  "inventory.adjustSuccess": "Stock adjusted successfully",
  "inventory.comboboxPlaceholder": "Type SKU or product name...",
  "inventory.comboboxEmpty": "No product found",

  "pos.title": "POS Sale",
  "pos.description": "Search products, add to cart, create draft, update draft and checkout.",
  "pos.searchProduct": "Search SKU, product name, description or QR...",
  "pos.allProducts": "All",
  "pos.addToCart": "Add to cart",
  "pos.outOfStock": "Out of stock",
  "pos.cart": "Cart",
  "pos.findCustomer": "Find customer",
  "pos.customerPlaceholder": "Customer name/phone",
  "pos.find": "Find",
  "pos.paymentMethod": "Payment method",
  "pos.createDraft": "Create draft",
  "pos.updateDraft": "Update draft",
  "pos.checkout": "Checkout",
  "pos.subtotal": "Subtotal",
  "pos.discount": "Discount",
  "pos.totalPayable": "Total payable",
  "pos.draftCode": "Draft: {code}",
  "pos.draftCreated": "Draft created successfully",
  "pos.draftUpdated": "Draft updated successfully",
  "pos.checkoutSuccess": "Order paid successfully",
  "pos.noVoucher": "No Voucher",
  "pos.manualDiscount": "Manual discount",
  "pos.voucherHelp": "Select an eligible voucher for this order",
  "pos.manualDiscountHelp": "Manual discount for the entire invoice",
  "toast.pos.voucherApplied": "Voucher {code} applied.",
  "toast.pos.voucherAppliedWithAmount": "Voucher {code} applied, saved {amount}.",
  "toast.pos.manualDiscountAmountApplied": "Manual discount {amount} applied.",
  "toast.pos.manualDiscountPercentApplied": "Manual discount {percent}% applied.",
  "pos.voucher": "Voucher",
  "pos.apply": "Apply",
  "pos.noCart": "Please select products before checkout",
  "pos.quickCustomer": "Quick add customer at counter",
  "pos.quickCustomerDescription": "The new customer will be saved and selected immediately for the current POS order.",
  "pos.emptyCartHint": "Choose products on the left to add them to cart.",
  "pos.discountInputPlaceholder": "Enter amount or %, e.g. 50,000 or 10%",
  "pos.manualDiscountType": "Type",
  "pos.discountAmount": "Amount",
  "pos.discountPercent": "%",
  "pos.manualDiscountPlaceholderAmount": "50,000",
  "pos.manualDiscountPlaceholderPercent": "10",
  "pos.invalidDiscountAmount": "Invalid discount amount.",
  "pos.invalidDiscountPercent": "Discount percent must be from 1 to 100.",
  "pos.applyDiscount": "Apply",
  "pos.discountEmpty": "Please enter a voucher code or discount amount.",
  "pos.discountNeedCart": "Please add products before applying a discount.",
  "pos.discountApplied": "Discount {amount} applied.",
  "pos.discountPercentInvalid": "Discount percent must be greater than 0 and not exceed 100%.",
  "pos.discountAmountInvalid": "Invalid discount amount.",
  "pos.voucherInvalid": "Invalid voucher code or condition not met.",
  "pos.decreaseQuantity": "Decrease quantity",
  "pos.increaseQuantity": "Increase quantity",
  "pos.processingDraft": "Processing draft order",
  "pos.cancelOrder": "Cancel Order",
  "pos.cancelDraftTitle": "Cancel draft order",
  "pos.cancelDraftDescription": "Are you sure you want to cancel this draft order?",
  "pos.cancelDraftWarning": "This will mark the draft as cancelled, clear the current cart and reset POS to a new order state.",
  "pos.keepDraft": "Keep draft",
  "pos.confirmCancelDraft": "Confirm cancellation",

  "warranties.title": "Warranties",
  "warranties.description": "Warranty list, lookup by code, details and ADMIN actions.",
  "warranties.createManual": "Create manually",
  "warranties.searchPlaceholder": "Search warranty code, customer, phone",
  "warranties.warrantyCode": "Warranty code",
  "warranties.customer": "Customer",
  "warranties.product": "Product",
  "warranties.startDate": "Start date",
  "warranties.endDate": "End date",
  "warranties.lookupTitle": "Lookup by code",
  "warranties.lookupPlaceholder": "Enter warranty code",
  "warranties.lookup": "Lookup",
  "warranties.detailTitle": "Details {code}",
  "warranties.order": "Order",
  "warranties.productValue": "Line value",
  "warranties.cancelConfirm": "Cancel warranty {code}?",
  "warranties.restoreConfirm": "Restore warranty {code}?",
  "warranties.expireConfirm": "Set warranty {code} as expired?",
  "warranties.orderCode": "Order code",
  "warranties.orderCodePlaceholder": "Enter order code, e.g. HD202606071931388250",
  "warranties.orderCodeHint": "Enter a completed order code so the system can load the products in that order.",
  "warranties.findOrder": "Find order",
  "warranties.orderLoaded": "Order {code} loaded.",
  "warranties.orderNotFound": "No order was found for the entered code.",
  "warranties.orderCodeRequired": "Please enter an order code before searching.",
  "warranties.searchOrderFirst": "Please search for an order first",
  "warranties.chooseProductFromOrder": "Choose product from order",
  "warranties.chooseProductPlaceholder": "Choose the product to activate warranty",
  "warranties.chooseOrderProduct": "Please choose a product from the order to create warranty.",
  "warranties.hiddenOrderDetailHint": "The system automatically uses the hidden orderDetailId from the selected product; users do not need to type database row IDs.",
  "warranties.manualCreated": "Manual warranty created successfully",

  "payments.title": "Payments",
  "payments.description": "Manage cash flow, payment channels, reconciliation vouchers and transaction refunds.",
  "payments.searchPlaceholder": "Enter transaction or order code...",
  "payments.id": "Payment ID",
  "payments.order": "Order",
  "payments.method": "Payment Method",
  "payments.amount": "Amount",
  "payments.paidAt": "Payment Date",
  "payments.findByOrder": "Find payment by Order ID",
  "payments.orderIdPlaceholder": "Enter order ID...",
  "payments.noPaymentSelected": "No payment selected",
  "payments.detailTitle": "Payment details #{id}",
  "payments.refund": "Refund",
  "payments.refundConfirm": "Are you sure you want to refund transaction {code}?",
  "payments.transactionId": "Transaction ID",
  "payments.linkedOrderCode": "Linked Order Code",
  "payments.amountPaid": "Amount Paid",
  "payments.viewVoucher": "View Voucher",
  "payments.refundTransaction": "Refund Transaction",
  "payments.refundSuccess": "Transaction {code} refunded successfully.",
  "payments.voucherTitle": "Payment voucher {code}",
  "payments.reconcileCode": "Reconciliation Code",
  "payments.cashflowStatus": "Cash Flow Status",
  "payments.internalOrderId": "Internal Order ID",

  "reports.title": "Reports",
  "reports.description": "Revenue, top products, low-stock and customer reports.",
  "reports.fromDate": "From date",
  "reports.toDate": "To date",
  "reports.apply": "Apply",
  "reports.summary": "Summary",
  "reports.revenueChart": "Daily revenue",
  "reports.profitChart": "Revenue, COGS and profit",
  "reports.topProducts": "Top selling products",
  "reports.topCustomers": "Top customers",
  "reports.lowStock": "Low-stock products",
  "reports.customers": "Customers",
  "reports.quantity": "Quantity",
  "reports.revenue": "Revenue",
  "reports.cogs": "COGS",
  "reports.netProfit": "Net profit",
  "reports.totalSpent": "Total spent",
  "reports.totalOrders": "Orders",
  "reports.latestOrder": "Latest order",
  "reports.noProfitData": "No revenue, COGS or profit data in the selected date range.",
  "reports.noTopProductData": "No top product data in the selected date range.",

  "users.title": "Employees",
  "users.description": "Administrators create login codes, update, lock, restore and change employee passwords.",
  "users.add": "Add employee",
  "users.searchPlaceholder": "Search name, employee code, email, phone",
  "users.employeeCode": "Employee code",
  "users.employeeCodeAuto": "Auto generated if empty",
  "users.emailOptional": "Contact email (optional)",
  "users.fullName": "Full name",
  "users.password": "Password",
  "users.newPassword": "New password",
  "users.createTitle": "Create employee",
  "users.updateTitle": "Update {email}",
  "users.changePasswordTitle": "Change password {email}",
  "users.changePassword": "Change password",
  "users.lock": "Lock",
  "users.unlock": "Restore",
  "users.createSuccess": "Employee created successfully",
  "users.updateSuccess": "Employee updated successfully",
  "users.passwordSuccess": "Password changed successfully. New password: {password}",
  "users.lockConfirm": "Lock account {email}?",
  "users.restoreConfirm": "Restore account {email}?",
  "users.lastLoginAt": "Last login",
  "users.validationRequired": "Please enter required information",
  "users.validationEmail": "Invalid email",
  "users.validationPassword": "Password must be at least 6 characters",

  "audit.title": "Audit Logs",
  "audit.description": "Track system actions and filter by action, entity, user and date range.",
  "audit.searchPlaceholder": "Search action, entity, description...",
  "audit.action": "Action",
  "audit.entityType": "Entity Type",
  "audit.entityId": "Entity ID",
  "audit.userIdFilter": "User ID",
  "audit.user": "User",
  "audit.descriptionField": "Description",
  "audit.detailTitle": "Log details #{id}",
  "audit.oldValue": "Old Value",
  "audit.newValue": "New Value",

  "promotions.title": "Promotions",
  "promotions.description": "Manage voucher codes, minimum order conditions, usage limits and expiration dates.",
  "promotions.add": "Add promotion",
  "promotions.searchPlaceholder": "Search promotion code...",
  "promotions.code": "Promotion Code",
  "promotions.discountType": "Discount Type",
  "promotions.discountValue": "Discount Value",
  "promotions.minOrderAmount": "Minimum Order",
  "promotions.amountType": "Fixed Amount",
  "promotions.percentType": "Invoice Percentage",
  "promotions.usedUp": "Used Up",
  "promotions.createTitle": "Create Promotion",
  "promotions.editTitle": "Update Promotion",
  "promotions.formDescription": "Enter promotion details to apply it on the POS screen.",
  "promotions.usageLimit": "Usage Limit",
  "promotions.unlimited": "Unlimited",
  "promotions.expiredAt": "Expiration Date",
  "promotions.created": "Promotion created successfully.",
  "promotions.updated": "Promotion updated successfully.",
  "promotions.deleted": "Promotion deleted successfully.",
  "promotions.deleteConfirm": "Delete promotion {code}?",
  "promotions.formInvalid": "Please enter code, discount value and expiration date.",
  "promotions.quantity": "Remaining",
  "promotions.remainingQuantity": "Remaining Quantity",
  "promotions.codePlaceholder": "Example: HOMEX50K",
  "promotions.discountValueMoneyPlaceholder": "Example: 50,000 VND",
  "promotions.discountValuePercentPlaceholder": "Example: 10%",
  "promotions.minOrderAmountPlaceholder": "Example: 200,000 VND",
  "promotions.percentInvalid": "Discount percentage must be greater than 0 and not exceed 100%.",
  "promotions.apiNotMounted": "Promotion API has not been mounted in the backend.",
  "promotions.backendNotConfigured": "Promotion backend model or migration is not fully configured.",

  "auth.checkingPermission": "Checking access permission",
  "auth.noPermission": "Access denied",
  "auth.noPermissionDescription": "This function is only available for authorized roles.",
  "auth.currentNoPermission": "The current account is not allowed to use this function.",
  "auth.backDashboard": "Back to Dashboard",

  "home.redirecting": "Redirecting",
};

const megaVi: Dictionary = {
  "demo.restriction": "Chế độ demo chỉ cho phép xem dữ liệu. Thao tác ghi đã bị chặn.",
  "network.offlineWarning": "Bạn đang offline. Các thao tác bán hàng cần kết nối mạng.",
  "network.checkoutDisabled": "Không thể checkout khi offline. Vui lòng kết nối mạng.",
  "errorBoundary.title": "Trang gặp lỗi hiển thị",
  "errorBoundary.description": "Bạn có thể thử tải lại phần nội dung này mà không mất phiên đăng nhập.",
  "errorBoundary.retry": "Thử lại",
  "common.export": "Xuất CSV",
  "nav.settings": "Cài đặt",
  "nav.purchaseOrders": "Phiếu nhập",
  "nav.returnOrders": "Trả hàng",
  "nav.shifts": "Ca làm",
  "nav.vatInvoices": "Hóa đơn VAT",
  "products.originalPrice": "Giá gốc",
  "pos.cashReceived": "Tiền khách đưa",
  "pos.cashReceivedPlaceholder": "Nhập tiền khách đưa",
  "pos.cashCheckoutTitle": "Thanh toán tiền mặt",
  "pos.cashCheckoutDescription": "Nhập số tiền khách đưa để hệ thống tự tính tiền thối trước khi hoàn tất hóa đơn.",
  "pos.changeAmount": "Tiền thối",
  "pos.cashNotEnough": "Tiền khách đưa chưa đủ.",
  "pos.confirmPayment": "Xác nhận thanh toán",
  "pos.confirmOrderTitle": "Xác nhận đơn hàng",
  "pos.confirmOrderDescription": "Kiểm tra sản phẩm, khách hàng và tổng tiền trước khi thanh toán.",
  "pos.orderItems": "Sản phẩm trong đơn",
  "pos.continueToCash": "Tiếp tục nhập tiền mặt",
  "pos.continueToQr": "Tiếp tục tạo QR",
  "pos.qrPaymentTitle": "Thanh toán chuyển khoản QR",
  "pos.qrPaymentDescription": "Yêu cầu khách chuyển khoản đúng số tiền và nội dung, sau đó xác nhận đã nhận tiền.",
  "pos.beneficiary": "Tài khoản thụ hưởng",
  "pos.transferContent": "Nội dung chuyển khoản",
  "pos.confirmReceivedTransfer": "Xác nhận đã nhận tiền",
  "pos.bankNotConfigured": "Chưa cấu hình tài khoản thụ hưởng.",
  "pos.receiptTitle": "Hóa đơn đã hoàn tất",
  "pos.receiptDescription": "In, tải hóa đơn hoặc bắt đầu đơn hàng mới.",
  "pos.newOrder": "Đơn mới",
  "pos.downloadInvoice": "Tải xuống",
  "pos.cashier": "Thu ngân",
  "pos.barcodeInput": "Ô quét barcode",
  "pos.barcodeAdded": "Đã thêm sản phẩm {sku} vào giỏ.",
  "pos.barcodeOutOfStock": "Sản phẩm quét được đã hết hàng.",
  "pos.barcodeNotFound": "Không tìm thấy sản phẩm theo barcode.",
  "invoice.title": "Hóa đơn bán hàng",
  "invoice.hotline": "Hotline",
  "invoice.scanPublic": "Quét để xem hóa đơn online",
  "invoice.thankYou": "Cảm ơn quý khách",
  "invoice.publicTitle": "Tra cứu hóa đơn",
  "invoice.lastReady": "Hóa đơn {code} đã sẵn sàng để in.",
  "settings.title": "Cài đặt hệ thống",
  "settings.description": "Quản lý thông tin cửa hàng, in hóa đơn, ngân hàng và quy tắc bán hàng.",
  "settings.storeInfo": "Thông tin cửa hàng",
  "settings.storeName": "Tên cửa hàng",
  "settings.storeBranch": "Chi nhánh",
  "settings.taxCode": "Mã số thuế",
  "settings.businessHours": "Giờ hoạt động",
  "settings.currency": "Tiền tệ",
  "settings.storeAddress": "Địa chỉ cửa hàng",
  "settings.storeHotline": "Hotline",
  "settings.printAndBank": "In hóa đơn và ngân hàng",
  "settings.posSection": "POS",
  "settings.printSection": "Hóa đơn in ấn",
  "settings.inventorySection": "Kho hàng",
  "settings.vietQrSection": "Chuyển khoản VietQR",
  "settings.permissionSection": "Phân quyền thao tác",
  "settings.printPaperSize": "Khổ in",
  "settings.printCopies": "Số bản in",
  "settings.autoOpenPrint": "Tự mở in sau thanh toán",
  "settings.requireCustomerPhone": "Nhắc nhập SĐT khách hàng",
  "settings.bankName": "Ngân hàng",
  "settings.bankAccountNumber": "Số tài khoản",
  "settings.bankAccountName": "Tên tài khoản",
  "settings.vietQrTemplate": "Mẫu VietQR",
  "settings.transferContentTemplate": "Nội dung chuyển khoản mặc định",
  "settings.businessRules": "Quy tắc bán hàng",
  "settings.defaultPaymentMethod": "Thanh toán mặc định",
  "settings.productsPerPage": "Số sản phẩm mỗi trang",
  "settings.autoLockMinutes": "Tự khóa sau phút",
  "settings.allowOrderDiscount": "Cho phép chiết khấu đơn hàng",
  "settings.confirmBeforeCheckout": "Xác nhận trước khi thanh toán",
  "settings.barcodeAutoAdd": "Quét mã tự thêm vào giỏ",
  "settings.compactPosMode": "Giao diện POS thu gọn",
  "settings.minStock": "Tồn tối thiểu mặc định",
  "settings.warnLowStockSale": "Cảnh báo khi bán tồn thấp",
  "settings.allowOversell": "Cho phép bán vượt tồn",
  "settings.maxDiscount": "Giảm giá tối đa",
  "settings.exportConfig": "Xuất JSON",
  "settings.importConfig": "Nhập JSON",
  "settings.invalidConfig": "File cấu hình không hợp lệ",
  "settings.adminPermissionSummary": "Toàn quyền quản trị dữ liệu, báo cáo, nhân viên, cài đặt và thao tác nhạy cảm.",
  "settings.cashierPermissionSummary": "Được bán hàng, xem hóa đơn, khách hàng, bảo hành, ca làm và tra cứu dữ liệu cần thiết.",
  "status.APPROVED": "Đã duyệt",
  "status.REJECTED": "Đã hủy",
  "status.OPEN": "Đang mở",
  "status.CLOSED": "Đã đóng",
  "shifts.title": "Ca làm thu ngân",
  "shifts.description": "Theo dõi ca mở/đóng, tiền đầu ca, tiền cuối ca và lệch tiền.",
  "shifts.currentOpen": "Ca hiện tại đang mở",
  "shifts.noOpen": "Chưa mở ca",
  "shifts.required": "Thu ngân cần mở ca trước khi thanh toán.",
  "shifts.open": "Mở ca",
  "shifts.close": "Đóng ca",
  "shifts.refresh": "Làm mới",
  "shifts.opened": "Mở ca thành công.",
  "shifts.closed": "Đóng ca thành công. Lệch tiền: {amount}.",
  "shifts.openingCash": "Tiền đầu ca",
  "shifts.closingCash": "Tiền cuối ca",
  "shifts.expectedCash": "Tiền dự kiến",
  "shifts.discrepancy": "Lệch tiền",
  "shifts.totalShifts": "Tổng ca",
  "shifts.cashier": "Thu ngân",
  "shifts.openedAt": "Mở ca",
  "shifts.closedAt": "Đóng ca",
  "shifts.notePlaceholder": "Ghi chú ca làm",
  "shifts.adminScope": "Quản trị viên đang xem tất cả ca làm",
  "shifts.cashierScope": "Thu ngân chỉ xem ca của mình",
  "shifts.empty": "Chưa có ca làm nào",
  "vat.title": "Yêu cầu hóa đơn VAT",
  "vat.description": "Duyệt, hủy và nhập mã hóa đơn đỏ cho yêu cầu của khách.",
  "vat.searchPlaceholder": "Tìm mã đơn, công ty hoặc mã số thuế",
  "vat.requestTitle": "Yêu cầu hóa đơn VAT",
  "vat.companyName": "Tên công ty",
  "vat.taxCode": "Mã số thuế",
  "vat.companyAddress": "Địa chỉ công ty",
  "vat.redInvoiceCode": "Mã hóa đơn đỏ",
  "vat.adminNote": "Ghi chú xử lý",
  "vat.approve": "Duyệt",
  "vat.reject": "Hủy",
  "vat.approved": "Đã duyệt yêu cầu VAT.",
  "vat.rejected": "Đã hủy yêu cầu VAT.",
  "vat.submitRequest": "Gửi yêu cầu VAT",
  "vat.requestSent": "Đã gửi yêu cầu VAT.",
  "purchaseOrders.title": "Phiếu nhập kho",
  "purchaseOrders.description": "Tạo phiếu nhập theo nhà cung cấp và cập nhật tồn kho.",
  "purchaseOrders.createTitle": "Tạo phiếu nhập",
  "purchaseOrders.addItem": "Thêm dòng hàng",
  "purchaseOrders.created": "Tạo phiếu nhập thành công.",
  "returnOrders.title": "Trả hàng",
  "returnOrders.description": "Tạo phiếu trả hàng từ hóa đơn cũ và hoàn kho.",
  "returnOrders.createTitle": "Tạo phiếu trả hàng",
  "returnOrders.orderNotFound": "Không tìm thấy hóa đơn đã hoàn tất.",
  "returnOrders.returnQuantity": "Số lượng trả",
  "returnOrders.reason": "Lý do trả hàng",
  "returnOrders.create": "Tạo phiếu trả",
  "returnOrders.created": "Tạo phiếu trả hàng thành công.",
  "notifications.title": "Thông báo",
  "notifications.empty": "Chưa có thông báo",
  "notifications.markAllRead": "Đã đọc tất cả",
  "customers.fullNamePlaceholder": "Nhập họ tên",
  "customers.phonePlaceholder": "Nhập số điện thoại",
  "customers.emailPlaceholder": "Nhập email",
  "customers.addressPlaceholder": "Nhập địa chỉ",
  "customers.notePlaceholder": "Ghi chú",
};

const megaEn: Dictionary = {
  "demo.restriction": "Demo mode only allows viewing data. Write actions are blocked.",
  "network.offlineWarning": "You are offline. Sales actions require network connection.",
  "network.checkoutDisabled": "Checkout is disabled while offline. Please reconnect.",
  "errorBoundary.title": "This page hit a display error",
  "errorBoundary.description": "You can retry this content without losing your login session.",
  "errorBoundary.retry": "Retry",
  "common.export": "Export CSV",
  "nav.settings": "Settings",
  "nav.purchaseOrders": "Purchase Orders",
  "nav.returnOrders": "Returns",
  "nav.shifts": "Shifts",
  "nav.vatInvoices": "VAT Invoices",
  "products.originalPrice": "Original price",
  "pos.cashReceived": "Cash received",
  "pos.cashReceivedPlaceholder": "Enter cash received",
  "pos.cashCheckoutTitle": "Cash payment",
  "pos.cashCheckoutDescription": "Enter the cash received so the system can calculate change before completing the invoice.",
  "pos.changeAmount": "Change",
  "pos.cashNotEnough": "Cash received is not enough.",
  "pos.confirmPayment": "Confirm payment",
  "pos.confirmOrderTitle": "Confirm order",
  "pos.confirmOrderDescription": "Review items, customer and total before checkout.",
  "pos.orderItems": "Order items",
  "pos.continueToCash": "Continue to cash",
  "pos.continueToQr": "Continue to QR",
  "pos.qrPaymentTitle": "QR bank transfer payment",
  "pos.qrPaymentDescription": "Ask the customer to transfer the exact amount and content, then confirm receipt.",
  "pos.beneficiary": "Beneficiary account",
  "pos.transferContent": "Transfer content",
  "pos.confirmReceivedTransfer": "Confirm money received",
  "pos.bankNotConfigured": "Beneficiary account is not configured.",
  "pos.receiptTitle": "Invoice completed",
  "pos.receiptDescription": "Print, download the invoice or start a new order.",
  "pos.newOrder": "New order",
  "pos.downloadInvoice": "Download",
  "pos.cashier": "Cashier",
  "pos.barcodeInput": "Barcode scan input",
  "pos.barcodeAdded": "Added product {sku} to cart.",
  "pos.barcodeOutOfStock": "Scanned product is out of stock.",
  "pos.barcodeNotFound": "No product found for this barcode.",
  "invoice.title": "Sales Invoice",
  "invoice.hotline": "Hotline",
  "invoice.scanPublic": "Scan to view this invoice online",
  "invoice.thankYou": "Thank you",
  "invoice.publicTitle": "Invoice Lookup",
  "invoice.lastReady": "Invoice {code} is ready to print.",
  "settings.title": "System Settings",
  "settings.description": "Manage store info, invoice printing, bank account and sales rules.",
  "settings.storeInfo": "Store Information",
  "settings.storeName": "Store name",
  "settings.storeBranch": "Branch",
  "settings.taxCode": "Tax code",
  "settings.businessHours": "Business hours",
  "settings.currency": "Currency",
  "settings.storeAddress": "Store address",
  "settings.storeHotline": "Hotline",
  "settings.printAndBank": "Printing and bank",
  "settings.posSection": "POS",
  "settings.printSection": "Invoice printing",
  "settings.inventorySection": "Inventory",
  "settings.vietQrSection": "VietQR bank transfer",
  "settings.permissionSection": "Action permissions",
  "settings.printPaperSize": "Print size",
  "settings.printCopies": "Print copies",
  "settings.autoOpenPrint": "Open print after checkout",
  "settings.requireCustomerPhone": "Prompt for customer phone",
  "settings.bankName": "Bank",
  "settings.bankAccountNumber": "Account number",
  "settings.bankAccountName": "Account name",
  "settings.vietQrTemplate": "VietQR template",
  "settings.transferContentTemplate": "Default transfer content",
  "settings.businessRules": "Business rules",
  "settings.defaultPaymentMethod": "Default payment method",
  "settings.productsPerPage": "Products per page",
  "settings.autoLockMinutes": "Auto lock after minutes",
  "settings.allowOrderDiscount": "Allow order discount",
  "settings.confirmBeforeCheckout": "Confirm before checkout",
  "settings.barcodeAutoAdd": "Scan code auto-adds to cart",
  "settings.compactPosMode": "Compact POS interface",
  "settings.minStock": "Default minimum stock",
  "settings.warnLowStockSale": "Warn on low-stock sale",
  "settings.allowOversell": "Allow overselling",
  "settings.maxDiscount": "Maximum discount",
  "settings.exportConfig": "Export JSON",
  "settings.importConfig": "Import JSON",
  "settings.invalidConfig": "Invalid configuration file",
  "settings.adminPermissionSummary": "Full access to data, reports, employees, settings and sensitive operations.",
  "settings.cashierPermissionSummary": "Can sell, view invoices, customers, warranties, shifts and required lookup data.",
  "status.APPROVED": "Approved",
  "status.REJECTED": "Rejected",
  "status.OPEN": "Open",
  "status.CLOSED": "Closed",
  "shifts.title": "Cashier Shifts",
  "shifts.description": "Track shift opening, closing cash and cash discrepancy.",
  "shifts.currentOpen": "Current shift is open",
  "shifts.noOpen": "No open shift",
  "shifts.required": "Cashiers must open a shift before checkout.",
  "shifts.open": "Open shift",
  "shifts.close": "Close shift",
  "shifts.refresh": "Refresh",
  "shifts.opened": "Shift opened successfully.",
  "shifts.closed": "Shift closed successfully. Difference: {amount}.",
  "shifts.openingCash": "Opening cash",
  "shifts.closingCash": "Closing cash",
  "shifts.expectedCash": "Expected cash",
  "shifts.discrepancy": "Discrepancy",
  "shifts.totalShifts": "Total shifts",
  "shifts.cashier": "Cashier",
  "shifts.openedAt": "Opened at",
  "shifts.closedAt": "Closed at",
  "shifts.notePlaceholder": "Shift note",
  "shifts.adminScope": "Administrators are viewing all shifts",
  "shifts.cashierScope": "Cashiers only view their own shifts",
  "shifts.empty": "No shifts yet",
  "vat.title": "VAT Invoice Requests",
  "vat.description": "Approve, reject and enter red invoice codes for customer requests.",
  "vat.searchPlaceholder": "Search order, company or tax code",
  "vat.requestTitle": "VAT invoice request",
  "vat.companyName": "Company name",
  "vat.taxCode": "Tax code",
  "vat.companyAddress": "Company address",
  "vat.redInvoiceCode": "Red invoice code",
  "vat.adminNote": "Admin note",
  "vat.approve": "Approve",
  "vat.reject": "Reject",
  "vat.approved": "VAT request approved.",
  "vat.rejected": "VAT request rejected.",
  "vat.submitRequest": "Submit VAT request",
  "vat.requestSent": "VAT request submitted.",
  "purchaseOrders.title": "Purchase Orders",
  "purchaseOrders.description": "Create supplier purchase orders and update inventory.",
  "purchaseOrders.createTitle": "Create purchase order",
  "purchaseOrders.addItem": "Add item",
  "purchaseOrders.created": "Purchase order created successfully.",
  "returnOrders.title": "Returns",
  "returnOrders.description": "Create returns from existing invoices and restore inventory.",
  "returnOrders.createTitle": "Create return",
  "returnOrders.orderNotFound": "No completed order found.",
  "returnOrders.returnQuantity": "Return quantity",
  "returnOrders.reason": "Return reason",
  "returnOrders.create": "Create return",
  "returnOrders.created": "Return created successfully.",
  "notifications.title": "Notifications",
  "notifications.empty": "No notifications",
  "notifications.markAllRead": "Mark all read",
  "customers.fullNamePlaceholder": "Enter full name",
  "customers.phonePlaceholder": "Enter phone number",
  "customers.emailPlaceholder": "Enter email",
  "customers.addressPlaceholder": "Enter address",
  "customers.notePlaceholder": "Note",
};

const dictionaries: Record<Language, Dictionary> = { vi: { ...vi, ...megaVi }, en: { ...en, ...megaEn } };

const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(value: string, params?: TranslateParams) {
  if (!params) return value;

  return Object.entries(params).reduce((currentValue, [key, paramValue]) => {
    return currentValue.replaceAll(`{${key}}`, String(paramValue));
  }, value);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("vi");

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem("homex-pos-language");
    if (savedLanguage === "vi" || savedLanguage === "en") {
      setLanguageState(savedLanguage);
      document.documentElement.lang = savedLanguage;
    } else {
      document.documentElement.lang = "vi";
    }
  }, []);

  function setLanguage(nextLanguage: Language) {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("homex-pos-language", nextLanguage);
    document.documentElement.lang = nextLanguage;
  }

  function toggleLanguage() {
    setLanguage(language === "vi" ? "en" : "vi");
  }

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage,
      toggleLanguage,
      t: (key: string, params?: TranslateParams) => interpolate(dictionaries[language][key] || key, params),
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
